name: Install R package dependencies
description: |
  Instead of using `setup-r-dependencies` directly, we adopt the `remotes` based approach at
  https://github.com/r-lib/actions/blob/16f69b28bd300ec48b0182a6a8d4185e7f28781d/examples/check-full.yaml
  as `pak` may not work. See https://github.com/r-lib/actions/issues/431
  and https://github.com/r-lib/actions/issues/494.
inputs:
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache'
    required: true
    default: 1
  extra-packages:
    description: 'Any extra packages to install outside of the packages listed in the dependencies'
runs:
  using: 'composite'
  steps:
      - name: Query dependencies
        run: |
          install.packages('remotes', repos = "https://cran.rstudio.com/")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-${{ inputs.cache-version }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-${{ inputs.cache-version }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          # rocker/r-devel-ubsan-clang is debian, we just hope that the ubuntu packages will be same.
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
        shell: bash

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install extra packages
        run: |
          while read -r x; do
              Rscript -e "remotes::install_cran(\"$x\")"
          done <<< "${{ inputs.extra-packages }}"
        shell: bash
