name: Cancel Previous Runs
description: Cancel Previous Runs

runs:
  using: 'composite'
  steps:
    - uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
