name: Coverage Test for R package
description: Run coverage test for an R package

runs:
  using: 'composite'
  steps:
    - uses: r-lib/actions/setup-r@v1
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        extra-packages: covr

    - name: Test coverage
      run: covr::codecov()
      shell: Rscript {0}
